### ISSUE TITLE
Bug with nested objects

### ISSUE THREAD

**Issue by goloroden** [staygrimm/obj-subset#3]
I found a bug with nested objects.

When you have a nested object, and you are looking for a subset of it, it works, as long as the subset and the *entire* nested object match:

```javascript
original = {foo: 'a', bar: 'b', bas: { baz: 'c'}};
subset = {bas: { baz: 'c'}};
assert(isSubset(original, subset) === true); // Works fine :-)
```

This works, because the subset `{ baz: 'c' }` searched for is the entire nested object within the original. But when you only look for a partial nested object, it fails:

```javascript
original = {foo: 'a', bar: 'b', bas: { baz: 'c', bax: 'd'}};
subset = {bas: { baz: 'c'}};
assert(isSubset(original, subset) === true); // Does not work :-(
```

**Comment by goloroden** [comment]
I created a PR with tests that demo this behavior, and it also contains the fix for it :-)

**Comment by staygrimm** [comment]
Hey great catch!  Thanks a bunch for this.
